# Generated by Django 2.0.5 on 2018-08-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('rome_name', models.CharField(blank=True, db_column='rome_name', max_length=100, null=True)),
                ('mail_address', models.EmailField(db_column='mail_address', max_length=254)),
                ('password', models.CharField(db_column='password', max_length=250)),
                ('icon', models.ImageField(blank=True, db_column='icon', null=True, upload_to='static/images/')),
                ('introduction', models.TextField(blank=True, db_column='introduction', null=True)),
                ('plan_mail_address', models.EmailField(blank=True, db_column='plan_address', max_length=254, null=True)),
                ('plan_mail_time', models.TimeField(db_column='plan_time')),
                ('new_mail_address', models.EmailField(blank=True, db_column='new_address', max_length=254, null=True)),
                ('new_mail_stop_time', models.DateTimeField(db_column='mail_stop_time')),
                ('new_mail_start_time', models.DateTimeField(db_column='mail_start_time')),
                ('notice_signboard', models.BooleanField(db_column='notice_signboard')),
                ('notice_chat', models.BooleanField(db_column='notice_chat')),
                ('notice_calendar', models.BooleanField(db_column='notice_calendar')),
                ('notice_group', models.BooleanField(db_column='notice_group')),
            ],
        ),
    ]
