# Generated by Django 2.0.5 on 2019-02-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroupConnect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('plan_mail_time', models.TimeField(db_column='plan_mail_time')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='notice_group',
            field=models.BooleanField(default=True, verbose_name='グループ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='notice_signboard',
            field=models.BooleanField(default=True, verbose_name='掲示板'),
        ),
    ]
