# Generated by Django 2.0.5 on 2018-12-12 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroupConnect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signboard',
            name='group_id',
            field=models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, to='GroupConnect.Group'),
        ),
    ]
