# Generated by Django 2.2.dev20180717020843 on 2019-01-21 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroupConnect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(db_column='group_name', max_length=100, verbose_name='グループ名'),
        ),
        migrations.AlterField(
            model_name='group',
            name='notice',
            field=models.TextField(db_column='notice', null=True),
        ),
    ]
