# Generated by Django 2.0.5 on 2018-10-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroupConnect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('group_id', models.IntegerField(db_column='group_id')),
                ('event_list', models.IntegerField(db_column='event_list')),
                ('updated_at', models.DateTimeField(db_column='updated_at')),
                ('delete_at', models.DateTimeField(db_column='delete_at', default='None')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('sender_id', models.IntegerField(db_column='sender_id')),
                ('receiver_id', models.IntegerField(db_column='receiver_id')),
                ('updated_at', models.DateTimeField(db_column='updated_at')),
                ('deleted_at', models.DateTimeField(db_column='deleted_at', default='None')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=100)),
                ('description', models.CharField(db_column='description', default='None', max_length=100)),
                ('date_time', models.DateTimeField(db_column='date_time')),
                ('all_day', models.BooleanField(db_column='all_day')),
                ('repeat', models.CharField(db_column='repeat', max_length=100)),
                ('place', models.CharField(db_column='place', default='None', max_length=100)),
                ('notice', models.CharField(db_column='notice', default='None', max_length=100)),
                ('release', models.BooleanField(db_column='release', default='None')),
                ('scheduled', models.BooleanField(db_column='scheduled')),
                ('add_guest', models.TextField(db_column='add_guest')),
                ('authority_guest', models.BooleanField(db_column='authority_guest')),
                ('created_at', models.DateTimeField(db_column='created_at')),
                ('updated_at', models.DateTimeField(db_column='updated_at')),
                ('deleted_at', models.DateTimeField(db_column='deleted_at', default='None')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('created_at', models.DateTimeField(db_column='created_at')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('group_name', models.CharField(db_column='group_name', max_length=100)),
                ('icon', models.ImageField(blank=True, db_column='icon', null=True, upload_to='static/images/')),
                ('create_date', models.DateTimeField(db_column='create_date')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(db_column='account_id')),
                ('group_id', models.IntegerField(db_column='group_id')),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('authority', models.BooleanField(db_column='authority')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('signboard_id', models.IntegerField(db_column='signboard_id')),
                ('text', models.TextField(db_column='text')),
                ('contributer', models.CharField(db_column='contributer', max_length=100)),
                ('posted', models.DateTimeField(db_column='posted')),
                ('read_number', models.IntegerField(db_column='read_number')),
            ],
        ),
        migrations.CreateModel(
            name='Signboard',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('group_id', models.IntegerField(db_column='group_id')),
                ('title', models.CharField(db_column='title', max_length=100)),
                ('category', models.CharField(db_column='category', max_length=100)),
                ('text', models.TextField(db_column='text')),
            ],
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('post_id', models.IntegerField(db_column='post_id')),
                ('account_id', models.IntegerField(db_column='account_id')),
                ('read_situation', models.CharField(db_column='read_situation', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('chat_id', models.IntegerField(db_column='chat_id')),
                ('text', models.TextField(db_column='text')),
                ('create_at', models.DateTimeField(db_column='create_at')),
                ('delete_at', models.DateTimeField(db_column='delete_at', default='None')),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='new_mail_address',
        ),
        migrations.RemoveField(
            model_name='account',
            name='plan_mail_address',
        ),
    ]
