# Generated by Django 2.2.dev20180717020843 on 2018-12-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroupConnect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupIcon',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('icon', models.ImageField(db_column='icon', upload_to='static/images/')),
            ],
        ),
    ]
