# Generated by Django 2.0.5 on 2019-02-07 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroupConnect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attached_file',
            field=models.FileField(blank=True, db_column='file', null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='post',
            name='reply',
            field=models.ForeignKey(blank=True, db_column='reply', null=True, on_delete=django.db.models.deletion.CASCADE, to='GroupConnect.Post'),
        ),
    ]
