# Generated by Django 2.0.5 on 2019-01-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroupConnect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signboard',
            name='updated_at',
            field=models.DateTimeField(db_column='updated_at', default=None),
            preserve_default=False,
        ),
    ]
