# Generated by Django 2.0.5 on 2018-10-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroupConnect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='notice_calendar',
            field=models.BooleanField(db_column='notice_calendar', default=True),
        ),
        migrations.AddField(
            model_name='account',
            name='notice_chat',
            field=models.BooleanField(db_column='notice_chat', default=True),
        ),
        migrations.AddField(
            model_name='account',
            name='notice_group',
            field=models.BooleanField(db_column='notice_group', default=True),
        ),
        migrations.AddField(
            model_name='account',
            name='notice_signboard',
            field=models.BooleanField(db_column='notice_signboard', default=True),
        ),
    ]
