# Generated by Django 2.2.dev20180717020843 on 2019-01-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroupConnect', '0002_auto_20190121_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='notice',
            field=models.TextField(db_column='notice', default=''),
        ),
    ]
