# Generated by Django 2.0.5 on 2019-01-16 05:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GroupConnect', '0002_signboard_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signboard',
            name='updated_at',
            field=models.DateTimeField(db_column='updated_at', default=django.utils.timezone.now),
        ),
    ]
