# Generated by Django 2.0.5 on 2019-01-18 03:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('GroupConnect', '0002_signboard_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signboard',
            name='updated_at',
            field=models.DateTimeField(db_column='updated_at', default=datetime.datetime(2019, 1, 18, 3, 12, 59, 122059, tzinfo=utc)),
        ),
    ]
