# Generated by Django 2.0.5 on 2019-01-30 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GroupConnect', '0004_auto_20190118_1214'),
        ('GroupConnect', '0003_auto_20190116_1448'),
    ]

    operations = [
    ]
