# Generated by Django 2.0.5 on 2019-01-31 04:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GroupConnect', '0005_merge_20190130_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attached_file',
            field=models.FileField(blank=True, db_column='attached_file', null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='post',
            name='reply',
            field=models.ForeignKey(blank=True, db_column='reply', null=True, on_delete=django.db.models.deletion.CASCADE, to='GroupConnect.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(db_column='created_at', default=django.utils.timezone.now),
        ),
    ]
